export const KEYCODES = [
  { code: 458756, mnemonic: "A", label: "A", group: "Letters" },
  { code: 458757, mnemonic: "B", label: "B", group: "Letters" },
  { code: 458758, mnemonic: "C", label: "C", group: "Letters" },
  { code: 458759, mnemonic: "D", label: "D", group: "Letters" },
  { code: 458760, mnemonic: "E", label: "E", group: "Letters" },
  { code: 458761, mnemonic: "F", label: "F", group: "Letters" },
  { code: 458762, mnemonic: "G", label: "G", group: "Letters" },
  { code: 458763, mnemonic: "H", label: "H", group: "Letters" },
  { code: 458764, mnemonic: "I", label: "I", group: "Letters" },
  { code: 458765, mnemonic: "J", label: "J", group: "Letters" },
  { code: 458766, mnemonic: "K", label: "K", group: "Letters" },
  { code: 458767, mnemonic: "L", label: "L", group: "Letters" },
  { code: 458768, mnemonic: "M", label: "M", group: "Letters" },
  { code: 458769, mnemonic: "N", label: "N", group: "Letters" },
  { code: 458770, mnemonic: "O", label: "O", group: "Letters" },
  { code: 458771, mnemonic: "P", label: "P", group: "Letters" },
  { code: 458772, mnemonic: "Q", label: "Q", group: "Letters" },
  { code: 458773, mnemonic: "R", label: "R", group: "Letters" },
  { code: 458774, mnemonic: "S", label: "S", group: "Letters" },
  { code: 458775, mnemonic: "T", label: "T", group: "Letters" },
  { code: 458776, mnemonic: "U", label: "U", group: "Letters" },
  { code: 458777, mnemonic: "V", label: "V", group: "Letters" },
  { code: 458778, mnemonic: "W", label: "W", group: "Letters" },
  { code: 458779, mnemonic: "X", label: "X", group: "Letters" },
  { code: 458780, mnemonic: "Y", label: "Y", group: "Letters" },
  { code: 458781, mnemonic: "Z", label: "Z", group: "Letters" },
  { code: 458782, mnemonic: "N1", label: "1", group: "Numbers" },
  { code: 458783, mnemonic: "N2", label: "2", group: "Numbers" },
  { code: 458784, mnemonic: "N3", label: "3", group: "Numbers" },
  { code: 458785, mnemonic: "N4", label: "4", group: "Numbers" },
  { code: 458786, mnemonic: "N5", label: "5", group: "Numbers" },
  { code: 458787, mnemonic: "N6", label: "6", group: "Numbers" },
  { code: 458788, mnemonic: "N7", label: "7", group: "Numbers" },
  { code: 458789, mnemonic: "N8", label: "8", group: "Numbers" },
  { code: 458790, mnemonic: "N9", label: "9", group: "Numbers" },
  { code: 458791, mnemonic: "N0", label: "0", group: "Numbers" },
  { code: 458841, mnemonic: "KP_N1", label: "Num 1", group: "Numpad" },
  { code: 458842, mnemonic: "KP_N2", label: "Num 2", group: "Numpad" },
  { code: 458843, mnemonic: "KP_N3", label: "Num 3", group: "Numpad" },
  { code: 458844, mnemonic: "KP_N4", label: "Num 4", group: "Numpad" },
  { code: 458845, mnemonic: "KP_N5", label: "Num 5", group: "Numpad" },
  { code: 458846, mnemonic: "KP_N6", label: "Num 6", group: "Numpad" },
  { code: 458847, mnemonic: "KP_N7", label: "Num 7", group: "Numpad" },
  { code: 458848, mnemonic: "KP_N8", label: "Num 8", group: "Numpad" },
  { code: 458849, mnemonic: "KP_N9", label: "Num 9", group: "Numpad" },
  { code: 458850, mnemonic: "KP_N0", label: "Num 0", group: "Numpad" },
  { code: 458839, mnemonic: "KP_PLUS", label: "Num +", group: "Numpad" },
  { code: 458838, mnemonic: "KP_MINUS", label: "Num -", group: "Numpad" },
  { code: 458837, mnemonic: "KP_MULTIPLY", label: "Num *", group: "Numpad" },
  { code: 458836, mnemonic: "KP_DIVIDE", label: "Num /", group: "Numpad" },
  { code: 458840, mnemonic: "KP_ENTER", label: "Num Enter", group: "Numpad" },
  { code: 458851, mnemonic: "KP_DOT", label: "Num .", group: "Numpad" },
  { code: 458855, mnemonic: "KP_EQUAL", label: "Num =", group: "Numpad" },
  { code: 458835, mnemonic: "KP_NUM", label: "Num Lock", group: "Numpad" },
  { code: 458810, mnemonic: "F1", label: "F1", group: "Function" },
  { code: 458811, mnemonic: "F2", label: "F2", group: "Function" },
  { code: 458812, mnemonic: "F3", label: "F3", group: "Function" },
  { code: 458813, mnemonic: "F4", label: "F4", group: "Function" },
  { code: 458814, mnemonic: "F5", label: "F5", group: "Function" },
  { code: 458815, mnemonic: "F6", label: "F6", group: "Function" },
  { code: 458816, mnemonic: "F7", label: "F7", group: "Function" },
  { code: 458817, mnemonic: "F8", label: "F8", group: "Function" },
  { code: 458818, mnemonic: "F9", label: "F9", group: "Function" },
  { code: 458819, mnemonic: "F10", label: "F10", group: "Function" },
  { code: 458820, mnemonic: "F11", label: "F11", group: "Function" },
  { code: 458821, mnemonic: "F12", label: "F12", group: "Function" },
  { code: 458792, mnemonic: "ENTER", label: "Enter", group: "Editing" },
  { code: 458793, mnemonic: "ESC", label: "Esc", group: "Editing" },
  { code: 458794, mnemonic: "BSPC", label: "Backspace", group: "Editing" },
  { code: 458828, mnemonic: "DEL", label: "Delete", group: "Editing" },
  { code: 458795, mnemonic: "TAB", label: "Tab", group: "Editing" },
  { code: 458796, mnemonic: "SPACE", label: "Space", group: "Editing" },
  { code: 458809, mnemonic: "CAPS", label: "Caps Lock", group: "Editing" },
  { code: 458825, mnemonic: "INS", label: "Insert", group: "Editing" },
  { code: 458826, mnemonic: "HOME", label: "Home", group: "Navigation" },
  { code: 458829, mnemonic: "END", label: "End", group: "Navigation" },
  { code: 458827, mnemonic: "PG_UP", label: "Page Up", group: "Navigation" },
  { code: 458830, mnemonic: "PG_DN", label: "Page Down", group: "Navigation" },
  { code: 458834, mnemonic: "UP", label: "Up", group: "Navigation" },
  { code: 458833, mnemonic: "DOWN", label: "Down", group: "Navigation" },
  { code: 458832, mnemonic: "LEFT", label: "Left", group: "Navigation" },
  { code: 458831, mnemonic: "RIGHT", label: "Right", group: "Navigation" },
  { code: 458976, mnemonic: "LCTRL", label: "Left Ctrl", group: "Modifiers" },
  { code: 458977, mnemonic: "LSHFT", label: "Left Shift", group: "Modifiers" },
  { code: 458978, mnemonic: "LALT", label: "Left Alt", group: "Modifiers" },
  { code: 458979, mnemonic: "LGUI", label: "Left GUI", group: "Modifiers" },
  { code: 458980, mnemonic: "RCTRL", label: "Right Ctrl", group: "Modifiers" },
  { code: 458981, mnemonic: "RSHFT", label: "Right Shift", group: "Modifiers" },
  { code: 458982, mnemonic: "RALT", label: "Right Alt", group: "Modifiers" },
  { code: 458983, mnemonic: "RGUI", label: "Right GUI", group: "Modifiers" },
  { code: 458797, mnemonic: "MINUS", label: "-", group: "Symbols" },
  { code: 458798, mnemonic: "EQUAL", label: "=", group: "Symbols" },
  { code: 458799, mnemonic: "LBKT", label: "[", group: "Symbols" },
  { code: 458800, mnemonic: "RBKT", label: "]", group: "Symbols" },
  { code: 458801, mnemonic: "BSLH", label: "\\", group: "Symbols" },
  { code: 458803, mnemonic: "SEMI", label: ";", group: "Symbols" },
  { code: 458804, mnemonic: "SQT", label: "'", group: "Symbols" },
  { code: 458805, mnemonic: "GRAVE", label: "`", group: "Symbols" },
  { code: 458806, mnemonic: "COMMA", label: ",", group: "Symbols" },
  { code: 458807, mnemonic: "DOT", label: ".", group: "Symbols" },
  { code: 458808, mnemonic: "FSLH", label: "/", group: "Symbols" },
  { code: 786658, mnemonic: "C_MUTE", label: "Mute", group: "Media" },
  { code: 786665, mnemonic: "C_VOL_UP", label: "Volume Up", group: "Media" },
  { code: 786666, mnemonic: "C_VOL_DN", label: "Volume Down", group: "Media" },
  { code: 786637, mnemonic: "C_PLAY_PAUSE", label: "Play / Pause", group: "Media" },
  { code: 786613, mnemonic: "C_NEXT", label: "Next Track", group: "Media" },
  { code: 786614, mnemonic: "C_PREV", label: "Prev Track", group: "Media" },
  { code: 786615, mnemonic: "C_STOP", label: "Stop", group: "Media" },
  { code: 786543, mnemonic: "C_BRI_UP", label: "Brightness Up", group: "Media" },
  { code: 786544, mnemonic: "C_BRI_DN", label: "Brightness Down", group: "Media" },
];
